services:
  postgres_pancmap_db:
    image: postgres
    container_name: postgres_pancmap_db
    restart: always
    ports:
      - 4457:5432
    env_file:
      - .env.test.local
    volumes:
      - postgres_pancmap_db:/var/lib/postgresql/data

  node_pancmap_app:
    container_name: node_pancmap_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - postgres_pancmap_db
    env_file:
      - .env.test.local

volumes:
  postgres_pancmap_db: