name: Pull Request Validator
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DATABASE_URL: "postgres://postgres:postgres@postgres_pancmap_db:5432/pancmap_test"
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "pancmap_test"
          envkey_JWT_SECRET: "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY2NDY2ODkyOCwiaWF0IjoxNjY0NjY4OTI4fQ.x0JLNMj0VZzsKr7XbsSK5YowCUo-S6jvxrTNWlT9NcI"
          file_name: .env.test.local
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node_pancmap_app npm run test